### ISSUE TITLE
Colcon build ros2 failed

### ISSUE THREAD

**Issue by Lshenni** [RRL-ALeRT/hector_slam_ros2#4]
Hi, i was trying to build the package with ros2 foxy, but i could get the colcon build to be complete... may i know how to solve this?

nvidia@nvidia-desktop:~/hector_ws$ colcon build --symlink-install --allow-overriding hector_map_tools hector_nav_msgs

ERROR FROM TERMINAL:

````
make[2]: *** [CMakeFiles/hector_mapping_node.dir/build.make:76: CMakeFiles/hector_mapping_node.dir/src/HectorMappingRos.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/hector_mapping_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Failed   <<< hector_mapping [43.7s, exited with code 2]

Summary: 5 packages finished [48.8s]
  1 package failed: hector_mapping
  1 package had stderr output: hector_mapping
  1 package not processed

```

**my hector_mapping/CMakeLists.txt file:
cmake_minimum_required(VERSION 3.8)
project(hector_mapping)**


---

set(CMAKE_CXX_STANDARD 14)

# Default to C99
if(NOT CMAKE_C_STANDARD)
  set(CMAKE_C_STANDARD 99)
endif()

# Default to C++14
if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 14)
endif()

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

set(ignoreMe "${FOO}${BAZ}${BAR}")

find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(nav_msgs REQUIRED)
find_package(std_srvs REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(visualization_msgs REQUIRED)
find_package(tf2 REQUIRED)
find_package(tf2_ros REQUIRED)
find_package(laser_geometry REQUIRED)
find_package(hector_nav_msgs REQUIRED)
find_package(pcl_conversions REQUIRED)

find_package(Boost REQUIRED COMPONENTS thread)

find_package(Eigen3 REQUIRED)

if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  # the following line skips the linter which checks for copyrights
  # uncomment the line when a copyright and license is not present in all source files
  #set(ament_cmake_copyright_FOUND TRUE)
  # the following line skips cpplint (only works in a git repo)
  # uncomment the line when this package is not in a git repo
  #set(ament_cmake_cpplint_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()
endif()

add_executable(hector_mapping_node src/main.cpp src/HectorMappingRos.cpp src/PoseInfoContainer.cpp)
include_directories("include/hector_slam_lib/")
ament_target_dependencies(hector_mapping_node rclcpp Boost tf2 tf2_ros sensor_msgs hector_nav_msgs std_srvs laser_geometry visualization_msgs pcl_conversions)

install(DIRECTORY launch
  DESTINATION share/${PROJECT_NAME}
)

install(TARGETS
  hector_mapping_node
  DESTINATION lib/${PROJECT_NAME})

ament_package()

```

**Comment by divindevaiah** [comment]
Change line https://github.com/RRL-ALeRT/hector_slam_ros2/blob/nuc/hector_mapping/src/HectorMappingRos.cpp#L212
and https://github.com/RRL-ALeRT/hector_slam_ros2/blob/nuc/hector_mapping/src/HectorMappingRos.cpp#L213

to

`  scanSubscriber_ = node_->create_subscription<sensor_msgs::msg::LaserScan>(p_scan_topic_, qos, std::bind(&HectorMappingRos::scanCallback, this, std::placeholders::_1));
`
and 
`
  sysMsgSubscriber_ = node_->create_subscription<std_msgs::msg::String>(p_sys_msg_topic_, 2, std::bind(&HectorMappingRos::sysMsgCallback, this, std::placeholders::_1));
`

**Comment by Lshenni** [comment]
Thank you but the problem still exists with other packages, 

Here is the new error from the terminal after making changes and rebuild the package:

`This may be promoted to an error in a future release of colcon-override-check.
Starting >>> hector_nav_msgs
Starting >>> hector_map_tools
Starting >>> hector_marker_drawing                            
Starting >>> sllidar_ros2                                     
Finished <<< hector_marker_drawing [1.53s]                              
Finished <<< hector_map_tools [1.73s]                                   
Finished <<< sllidar_ros2 [1.97s]                                        
Finished <<< hector_nav_msgs [4.59s]                     
Starting >>> hector_geotiff
Starting >>> hector_mapping
--- stderr: hector_geotiff   
![image](https://github.com/RRL-ALeRT/hector_slam_ros2/assets/75136333/a8fec195-e905-4f41-a3d9-dc9fcce61cb5)

`
